<?php
/**
 * Autoloader
 *
 * generated by my army of bots!
 *
 * PHP Version 5
 *
 * @category   Busmaster
 * @package    Server
 * @subpackage CLI
 * @author     Lucas S. Bickel <hairmare@purplehaze.ch>
 * @copyright  2012 Lucas S. Bickel 2011 - Alle Rechte vorbehalten
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link       http://osc.purplehaze.ch
 */
// @codeCoverageIgnoreStart

$map = array();

$map['ExampleAgent_Daemon'] = __DIR__.'./modules/ExampleAgent/Daemon.php';
$map['OscDispatch_Daemon'] = __DIR__.'./modules/OscDispatch/Daemon.php';
$map['OscReceive_Daemon'] = __DIR__.'./modules/OscReceive/Daemon.php';
